version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: blam92/player_app:latest
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet: